name: twoxko_wiki_glossary
description: "A Flutter eBook app showcasing the champion roster and fuse mechanics of the 2XKO game."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.5.5
  video_player: ^2.11.1
  youtube_player_flutter: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/champs/
    - assets/fuses/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/2XKO_Logo.png"
  min_sdk_android: 21